import { Button } from "@/components/ui/button";
import { ArrowLeft, AlertTriangle, ShieldCheck, Scale } from "lucide-react";
import { Link } from "wouter";

export default function RiskDisclosure() {
    return (
        <div className="min-h-screen w-full bg-background text-foreground p-6 md:p-12 overflow-y-auto">
            <div className="max-w-3xl mx-auto space-y-8 pb-12">
                <Link href="/">
                    <Button variant="ghost" size="sm" className="gap-2 mb-4">
                        <ArrowLeft className="w-4 h-4" />
                        Back to Chat
                    </Button>
                </Link>

                <div className="space-y-4">
                    <h1 className="text-4xl font-bold tracking-tight text-destructive-foreground bg-destructive px-4 py-2 rounded-lg inline-block">Risk Disclosure</h1>
                    <p className="text-muted-foreground italic">Essential Information for All Users</p>
                </div>

                <section className="bg-destructive/10 border border-destructive/20 p-6 rounded-xl space-y-4">
                    <div className="flex items-center gap-3 text-destructive font-bold">
                        <AlertTriangle className="w-6 h-6" />
                        <h2 className="text-2xl">High Risk Warning</h2>
                    </div>
                    <p className="leading-relaxed">
                        Trading cryptocurrencies, forex, commodities, and indices involves substantial risk and is not suitable for every investor. The high degree of leverage available can work against you as well as for you. Before deciding to trade, you should carefully consider your investment objectives, level of experience, and risk appetite.
                    </p>
                </section>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                    <section className="space-y-3 p-6 rounded-xl bg-card border border-border">
                        <div className="text-primary flex items-center gap-2 mb-2">
                            <ShieldCheck className="w-5 h-5" />
                            <h3 className="font-bold">Not Financial Advice</h3>
                        </div>
                        <p className="text-sm text-muted-foreground">
                            All content generated by Signalix V2 is for informational and educational purposes only. It should not be construed as investment, financial, or other advice.
                        </p>
                    </section>

                    <section className="space-y-3 p-6 rounded-xl bg-card border border-border">
                        <div className="text-primary flex items-center gap-2 mb-2">
                            <Scale className="w-5 h-5" />
                            <h3 className="font-bold">AI Accuracy</h3>
                        </div>
                        <p className="text-sm text-muted-foreground">
                            AI models can provide incorrect or misleading information. Technical patterns and historical data do not guarantee future results.
                        </p>
                    </section>
                </div>

                <section className="space-y-4">
                    <h2 className="text-2xl font-semibold underline decoration-destructive decoration-2">No Profit Guarantees</h2>
                    <p className="text-muted-foreground leading-relaxed">
                        There are NO guarantees of profit or freedom from loss in trading. Signalix V2 makes no representation that any account will or is likely to achieve profits or losses similar to those discussed on this platform.
                    </p>
                </section>

                <section className="space-y-4">
                    <h2 className="text-2xl font-semibold">Independent Evaluation</h2>
                    <p className="text-muted-foreground leading-relaxed">
                        Users must perform their own independent evaluation of the market and use their own judgment before placing any trades. You should only invest money that you can afford to lose.
                    </p>
                </section>

                <Separator className="my-8" />

                <p className="text-sm text-muted-foreground text-center">
                    &copy; 2026 Signalix V2. All rights reserved.
                </p>
            </div>
        </div>
    );
}

function Separator({ className }: { className?: string }) {
    return <div className={`h-[1px] w-full bg-border ${className}`} />;
}
